# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tcpclient.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_tcpclient_Dialog(object):
    def setupUi(self, tcpclient_Dialog):
        tcpclient_Dialog.setObjectName("tcpclient_Dialog")
        tcpclient_Dialog.resize(960, 700)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(tcpclient_Dialog.sizePolicy().hasHeightForWidth())
        tcpclient_Dialog.setSizePolicy(sizePolicy)
        self.label = QtWidgets.QLabel(tcpclient_Dialog)
        self.label.setGeometry(QtCore.QRect(10, 9, 111, 16))
        self.label.setObjectName("label")
        self.lineEdit_ipaddress = QtWidgets.QLineEdit(tcpclient_Dialog)
        self.lineEdit_ipaddress.setGeometry(QtCore.QRect(50, 40, 133, 20))
        self.lineEdit_ipaddress.setObjectName("lineEdit_ipaddress")
        self.label_3 = QtWidgets.QLabel(tcpclient_Dialog)
        self.label_3.setGeometry(QtCore.QRect(8, 70, 36, 16))
        self.label_3.setObjectName("label_3")
        self.pBtn_connectserver = QtWidgets.QPushButton(tcpclient_Dialog)
        self.pBtn_connectserver.setGeometry(QtCore.QRect(190, 30, 61, 31))
        self.pBtn_connectserver.setObjectName("pBtn_connectserver")
        self.pBtn_send = QtWidgets.QPushButton(tcpclient_Dialog)
        self.pBtn_send.setGeometry(QtCore.QRect(450, 150, 51, 31))
        self.pBtn_send.setObjectName("pBtn_send")
        self.label_4 = QtWidgets.QLabel(tcpclient_Dialog)
        self.label_4.setGeometry(QtCore.QRect(10, 120, 91, 16))
        self.label_4.setObjectName("label_4")
        self.label_2 = QtWidgets.QLabel(tcpclient_Dialog)
        self.label_2.setGeometry(QtCore.QRect(8, 40, 36, 16))
        self.label_2.setObjectName("label_2")
        self.lineEdit_port = QtWidgets.QLineEdit(tcpclient_Dialog)
        self.lineEdit_port.setGeometry(QtCore.QRect(50, 70, 133, 20))
        self.lineEdit_port.setObjectName("lineEdit_port")
        self.label_connectstatu = QtWidgets.QLabel(tcpclient_Dialog)
        self.label_connectstatu.setGeometry(QtCore.QRect(10, 100, 171, 16))
        self.label_connectstatu.setText("")
        self.label_connectstatu.setObjectName("label_connectstatu")
        self.pBtn_break = QtWidgets.QPushButton(tcpclient_Dialog)
        self.pBtn_break.setGeometry(QtCore.QRect(190, 70, 61, 31))
        self.pBtn_break.setObjectName("pBtn_break")
        self.label_5 = QtWidgets.QLabel(tcpclient_Dialog)
        self.label_5.setGeometry(QtCore.QRect(510, 120, 131, 16))
        self.label_5.setObjectName("label_5")
        self.textEdit = QtWidgets.QTextEdit(tcpclient_Dialog)
        self.textEdit.setGeometry(QtCore.QRect(10, 140, 431, 551))
        self.textEdit.setObjectName("textEdit")
        self.textBrowser = QtWidgets.QTextBrowser(tcpclient_Dialog)
        self.textBrowser.setGeometry(QtCore.QRect(510, 140, 431, 551))
        self.textBrowser.setObjectName("textBrowser")
        self.label_8 = QtWidgets.QLabel(tcpclient_Dialog)
        self.label_8.setGeometry(QtCore.QRect(260, 30, 281, 51))
        self.label_8.setObjectName("label_8")
        self.widget = QtWidgets.QWidget(tcpclient_Dialog)
        self.widget.setGeometry(QtCore.QRect(330, 110, 115, 22))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_6 = QtWidgets.QLabel(self.widget)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout.addWidget(self.label_6)
        self.lineEdit_timeout = QtWidgets.QLineEdit(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_timeout.sizePolicy().hasHeightForWidth())
        self.lineEdit_timeout.setSizePolicy(sizePolicy)
        self.lineEdit_timeout.setMaximumSize(QtCore.QSize(41, 20))
        self.lineEdit_timeout.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_timeout.setObjectName("lineEdit_timeout")
        self.horizontalLayout.addWidget(self.lineEdit_timeout)
        self.label_7 = QtWidgets.QLabel(self.widget)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout.addWidget(self.label_7)

        self.retranslateUi(tcpclient_Dialog)
        QtCore.QMetaObject.connectSlotsByName(tcpclient_Dialog)

    def retranslateUi(self, tcpclient_Dialog):
        _translate = QtCore.QCoreApplication.translate
        tcpclient_Dialog.setWindowTitle(_translate("tcpclient_Dialog", "TCP Fake"))
        self.label.setText(_translate("tcpclient_Dialog", "1.连接TCP服务端"))
        self.lineEdit_ipaddress.setText(_translate("tcpclient_Dialog", "192.168.1.1"))
        self.label_3.setText(_translate("tcpclient_Dialog", "端口号"))
        self.pBtn_connectserver.setText(_translate("tcpclient_Dialog", "连接"))
        self.pBtn_send.setText(_translate("tcpclient_Dialog", "发送"))
        self.label_4.setText(_translate("tcpclient_Dialog", "2.发送消息"))
        self.label_2.setText(_translate("tcpclient_Dialog", "IP地址"))
        self.lineEdit_port.setText(_translate("tcpclient_Dialog", "8000"))
        self.pBtn_break.setText(_translate("tcpclient_Dialog", "断开"))
        self.label_5.setText(_translate("tcpclient_Dialog", "3.接收消息"))
        self.label_8.setText(_translate("tcpclient_Dialog", "<html><head/><body><p>使用的是短连接，输入内容直接点击发送即可。</p><p>本地tcp服务端ip为127.0.0.1:9999</p></body></html>"))
        self.label_6.setText(_translate("tcpclient_Dialog", "超时时间"))
        self.lineEdit_timeout.setText(_translate("tcpclient_Dialog", "1"))
        self.label_7.setText(_translate("tcpclient_Dialog", "秒"))

